# yaml-language-server: $schema=https://raw.githubusercontent.com/coveooss/json-schema-for-humans/main/config_schema.json

examples_as_yaml: true
collapse_long_descriptions: false
collapse_long_examples: false
deprecated_from_description: true
expand_buttons: true
with_footer: false
minify: false
show_breadcrumbs: true
show_toc: true
template_name: js
